### PR TITLE
Generate to stdout and given file

### PR DESCRIPTION
**Pull request by ph4r05**
This PR adds feature to generate data to stdout or to a file given in the configuration file.

Stdout is quite handy to redirect the stream directly to Booltest on diskless machines or to another post-processing tools.

Specifying filename in the config file is also handy so the user knows which file to look for after generator finishes.

### CODE REVIEW

**Comment by ph4r05** [comment]
Hmm I think it is common to log to stderr all the time. It also should be consistent between runs with different parameters so it can be redirected with `2>` all the time.

**Comment by mitko501** [comment]
Ok then, I didn't know that. I don't have much experiences with bigger C++ projects. I will just check whether there are not more places where we log to stdout.

**Comment by ph4r05** [comment]
Thanks a lot for considering! I did not mean to be offensive or pushy, pardon me if I sounded like that.


I am currently using eacirc-streams quite a lot in our Booltest project so these PRs are few side effects that makes it easier to use. Hopefully this will help also others using this project. Thanks for that btw!

**Comment by mitko501** [comment]
No, you were not offensive or pushy I just wanted to discuss another approach which sounded better to me. But I don't have many experiences as I said, so you are most probably right. I really appreciate all your PRs. 

I send PR to your branch in which I updated eacirc-core version, I think we are ready to merge here after you merge my commit. Maybe we will just wait for Karel's review.

**Comment by Bender250** [comment]
I agree with the changes, yet I have not tested it. Approved to merge.

**Comment by ph4r05** [comment]
@mitko501 merged, thanks!

**Comment by mitko501** [comment]
@ph4r05 thanks

**Pull request merged**
